# Generated by Django 6.0.5 on 2026-05-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=20)),
                ('activity_type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=20)),
                ('emissions_kg_co2e', models.FloatField()),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('approval_status', models.CharField(default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawrecord')),
            ],
        ),
    ]
